import { useState, useEffect, useRef, useCallback } from 'react';
import { motion } from 'framer-motion';
import jsQR from 'jsqr';
import { usePartyStore } from '@/store/usePartyStore';
import { eventService } from '@/lib/events';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, QrCode, UserCheck, Camera, AlertCircle } from 'lucide-react';

/**
 * Parse a guest check-in QR payload.
 *
 * Canonical format (generated by server/routes/guests.ts):
 *   partyhause://checkin/{eventId}/{guestId}
 * A bare guest id is accepted as a legacy fallback.
 */
function parseCheckinPayload(raw: string): { eventId: string | null; guestId: string } | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  const match = /^partyhause:\/\/checkin\/([^/]+)\/([^/]+)$/.exec(trimmed);
  if (match) {
    return { eventId: match[1], guestId: match[2] };
  }

  // Legacy: a raw guest id (no URI scheme). Reject anything that looks like
  // a different URI to avoid checking in from unrelated QR codes.
  if (!trimmed.includes('://') && !trimmed.includes('/')) {
    return { eventId: null, guestId: trimmed };
  }

  return null;
}

/** Decode interval — decoding every frame burns CPU for no accuracy gain. */
const DECODE_INTERVAL_MS = 200;
/** Ignore repeat reads of the same payload within this window. */
const SAME_CODE_COOLDOWN_MS = 3000;

interface CameraQRReaderProps {
  onResult: (payload: string) => void;
}

const CameraQRReader = ({ onResult }: CameraQRReaderProps) => {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const rafRef = useRef<number | null>(null);
  const lastDecodeAtRef = useRef(0);
  const lastPayloadRef = useRef<{ value: string; at: number } | null>(null);
  const [cameraState, setCameraState] = useState<'idle' | 'starting' | 'active' | 'error'>('idle');
  const [cameraError, setCameraError] = useState<string | null>(null);

  const stopCamera = useCallback(() => {
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    }
    streamRef.current?.getTracks().forEach((track) => track.stop());
    streamRef.current = null;
    if (videoRef.current) {
      videoRef.current.srcObject = null;
    }
    setCameraState('idle');
  }, []);

  const scanFrame = useCallback(() => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !canvas) return;

    const now = Date.now();
    if (
      now - lastDecodeAtRef.current >= DECODE_INTERVAL_MS &&
      video.readyState === video.HAVE_ENOUGH_DATA &&
      video.videoWidth > 0
    ) {
      lastDecodeAtRef.current = now;
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext('2d', { willReadFrequently: true });
      if (ctx) {
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: 'dontInvert',
        });
        if (code && code.data) {
          const last = lastPayloadRef.current;
          if (!last || last.value !== code.data || now - last.at > SAME_CODE_COOLDOWN_MS) {
            lastPayloadRef.current = { value: code.data, at: now };
            onResult(code.data);
          }
        }
      }
    }

    rafRef.current = requestAnimationFrame(scanFrame);
  }, [onResult]);

  const startCamera = useCallback(async () => {
    if (cameraState === 'starting' || cameraState === 'active') return;
    setCameraState('starting');
    setCameraError(null);

    if (!navigator.mediaDevices?.getUserMedia) {
      setCameraState('error');
      setCameraError('Camera access is not supported in this browser.');
      return;
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment' },
        audio: false,
      });
      streamRef.current = stream;
      const video = videoRef.current;
      if (!video) {
        stream.getTracks().forEach((t) => t.stop());
        streamRef.current = null;
        setCameraState('idle');
        return;
      }
      video.srcObject = stream;
      await video.play();
      setCameraState('active');
      rafRef.current = requestAnimationFrame(scanFrame);
    } catch (err) {
      console.error('Camera start failed:', err);
      setCameraState('error');
      setCameraError(
        err instanceof DOMException && err.name === 'NotAllowedError'
          ? 'Camera permission denied. Allow camera access or use manual check-in below.'
          : 'Could not start the camera. Use manual check-in below.',
      );
    }
  }, [cameraState, scanFrame]);

  // Stop the camera on unmount.
  useEffect(() => stopCamera, [stopCamera]);

  return (
    <div className="relative aspect-square bg-secondary/20 rounded-lg border-2 border-dashed border-primary/30 flex items-center justify-center overflow-hidden">
      <video
        ref={videoRef}
        className={`absolute inset-0 w-full h-full object-cover ${cameraState === 'active' ? '' : 'hidden'}`}
        muted
        playsInline
      />
      <canvas ref={canvasRef} className="hidden" />

      {cameraState !== 'active' && (
        <div className="text-center px-6">
          <Camera className="h-16 w-16 mx-auto text-muted-foreground mb-4" />
          {cameraState === 'error' ? (
            <p className="text-destructive text-sm mb-4">{cameraError}</p>
          ) : (
            <p className="text-muted-foreground mb-4">
              Start the camera and point it at a guest's QR code
            </p>
          )}
          <Button onClick={startCamera} disabled={cameraState === 'starting'} className="btn-party">
            {cameraState === 'starting' ? 'Starting camera…' : 'Start Scanning'}
          </Button>
        </div>
      )}

      {cameraState === 'active' && (
        <Button
          onClick={stopCamera}
          variant="secondary"
          size="sm"
          className="absolute bottom-3 right-3 z-10"
        >
          Stop
        </Button>
      )}
    </div>
  );
};

export const QRScanner = () => {
  const { setCurrentPage, guests, updateGuest, currentEvent } = usePartyStore();
  const [scanResult, setScanResult] = useState<string | null>(null);
  const [scanStatus, setScanStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [manualCode, setManualCode] = useState('');
  const resultTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (resultTimerRef.current) clearTimeout(resultTimerRef.current);
    };
  }, []);

  const showResult = (status: 'success' | 'error', message: string) => {
    setScanStatus(status);
    setScanResult(message);
    if (resultTimerRef.current) clearTimeout(resultTimerRef.current);
    resultTimerRef.current = setTimeout(() => {
      setScanResult(null);
      setScanStatus('idle');
    }, 3000);
  };

  const checkInGuest = async (guestId: string) => {
    const guest = guests.find((g) => g.id === guestId);

    if (!guest) {
      showResult('error', 'Guest not found. Please check the QR code.');
      return;
    }

    if (guest.checked_in) {
      showResult('error', `${guest.name} is already checked in!`);
      return;
    }

    // Persist the check-in via the API, then mirror it in the store.
    const updated = await eventService.updateGuest(guestId, { checked_in: true });
    if (updated) {
      updateGuest(guestId, {
        checked_in: true,
        checked_in_at: updated.checked_in_at || new Date().toISOString(),
      });
      showResult('success', `${guest.name} has been checked in successfully!`);
    } else {
      showResult('error', `Failed to check in ${guest.name}. Please try again.`);
    }
  };

  const handleScan = async (rawPayload: string) => {
    const parsed = parseCheckinPayload(rawPayload);

    if (!parsed) {
      showResult('error', 'Unrecognized QR code — not a PartyHause check-in code.');
      return;
    }

    // QR payloads carry the event id — reject codes from a different event.
    if (parsed.eventId && currentEvent?.id && parsed.eventId !== currentEvent.id) {
      showResult('error', 'This QR code belongs to a different event.');
      return;
    }

    await checkInGuest(parsed.guestId);
  };

  const handleManualCheckIn = async () => {
    const code = manualCode.trim();
    if (!code) return;
    setManualCode('');
    await handleScan(code);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <motion.header 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="border-b border-border/50 bg-card/50 backdrop-blur-xl sticky top-0 z-10"
      >
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setCurrentPage('event-management')}
              className="mr-4"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Event
            </Button>
            <div>
              <h1 className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                QR Code Scanner
              </h1>
              <p className="text-muted-foreground">Scan guest QR codes to check them in</p>
            </div>
          </div>
        </div>
      </motion.header>

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-2xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <Card className="glass border-primary/20 shadow-2xl">
              <CardHeader className="text-center">
                <motion.div
                  animate={{ 
                    scale: [1, 1.1, 1],
                    rotate: [0, 5, -5, 0]
                  }}
                  transition={{ duration: 2, repeat: Infinity, repeatDelay: 1 }}
                  className="mx-auto mb-4"
                >
                  <QrCode className="h-16 w-16 text-primary animate-neon-flicker" />
                </motion.div>
                <CardTitle className="text-3xl">Check-In Scanner</CardTitle>
                <CardDescription className="text-lg">
                  Point your camera at a guest's QR code to check them in
                </CardDescription>
              </CardHeader>
              
              <CardContent className="space-y-6">
                {/* Scanner Area */}
                <div className="relative">
                  <CameraQRReader onResult={handleScan} />
                  
                  {/* Corner markers for scanner */}
                  <div className="absolute top-4 left-4 w-6 h-6 border-l-2 border-t-2 border-primary pointer-events-none" />
                  <div className="absolute top-4 right-4 w-6 h-6 border-r-2 border-t-2 border-primary pointer-events-none" />
                  <div className="absolute bottom-4 left-4 w-6 h-6 border-l-2 border-b-2 border-primary pointer-events-none" />
                  <div className="absolute bottom-4 right-4 w-6 h-6 border-r-2 border-b-2 border-primary pointer-events-none" />
                </div>

                {/* Manual fallback (camera denied/unavailable) */}
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={manualCode}
                    onChange={(e) => setManualCode(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') handleManualCheckIn();
                    }}
                    placeholder="Or paste a check-in code / guest ID"
                    className="input-shimmer flex-1 px-3 py-2 rounded-md border border-border bg-background text-sm"
                    aria-label="Manual check-in code"
                  />
                  <Button variant="outline" onClick={handleManualCheckIn} disabled={!manualCode.trim()}>
                    Check In
                  </Button>
                </div>

                {/* Scan Result */}
                {scanResult && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`p-4 rounded-lg border-2 ${
                      scanStatus === 'success' 
                        ? 'bg-accent/10 border-accent text-accent' 
                        : 'bg-destructive/10 border-destructive text-destructive'
                    }`}
                    role="status"
                    aria-live="polite"
                  >
                    <div className="flex items-center">
                      {scanStatus === 'success' ? (
                        <UserCheck className="h-5 w-5 mr-3" />
                      ) : (
                        <AlertCircle className="h-5 w-5 mr-3" />
                      )}
                      <p className="font-semibold">{scanResult}</p>
                    </div>
                  </motion.div>
                )}

                {/* Instructions */}
                <div className="bg-secondary/20 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2 flex items-center">
                    <QrCode className="h-4 w-4 mr-2 text-primary" />
                    How to scan:
                  </h3>
                  <ul className="text-sm text-muted-foreground space-y-1">
                    <li>• Ask guests to show their QR codes</li>
                    <li>• Center the QR code in the scanning area</li>
                    <li>• Wait for the automatic check-in confirmation</li>
                    <li>• The guest list will update in real-time</li>
                  </ul>
                </div>

                {/* Quick Stats */}
                <div className="grid grid-cols-2 gap-4 pt-4">
                  <div className="text-center bg-primary/10 rounded-lg p-4">
                    <div className="text-2xl font-bold text-primary">
                      {guests.filter(g => g.checked_in).length}
                    </div>
                    <div className="text-sm text-muted-foreground">Checked In</div>
                  </div>
                  <div className="text-center bg-accent/10 rounded-lg p-4">
                    <div className="text-2xl font-bold text-accent">
                      {guests.filter(g => !g.checked_in).length}
                    </div>
                    <div className="text-sm text-muted-foreground">Pending</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </div>
    </div>
  );
};
